//#line 2 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the gpu_stereo_image_proc package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __gpu_stereo_image_proc__LIBSGMCONFIG_H__
#define __gpu_stereo_image_proc__LIBSGMCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace gpu_stereo_image_proc
{
  class LIBSGMConfigStatics;

  class LIBSGMConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }

      virtual void clamp(LIBSGMConfig &config, const LIBSGMConfig &max, const LIBSGMConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const LIBSGMConfig &config1, const LIBSGMConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, LIBSGMConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const LIBSGMConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, LIBSGMConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const LIBSGMConfig &config) const = 0;
      virtual void getValue(const LIBSGMConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T LIBSGMConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T LIBSGMConfig::* field;

      virtual void clamp(LIBSGMConfig &config, const LIBSGMConfig &max, const LIBSGMConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const LIBSGMConfig &config1, const LIBSGMConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, LIBSGMConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const LIBSGMConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, LIBSGMConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const LIBSGMConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const LIBSGMConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, LIBSGMConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, LIBSGMConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<LIBSGMConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(LIBSGMConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("min_disparity"==(*_i)->name){min_disparity = boost::any_cast<int>(val);}
        if("disparity_range"==(*_i)->name){disparity_range = boost::any_cast<int>(val);}
        if("uniqueness_ratio"==(*_i)->name){uniqueness_ratio = boost::any_cast<double>(val);}
        if("path_type"==(*_i)->name){path_type = boost::any_cast<int>(val);}
        if("P1"==(*_i)->name){P1 = boost::any_cast<double>(val);}
        if("P2"==(*_i)->name){P2 = boost::any_cast<double>(val);}
      }
    }

    int min_disparity;
int disparity_range;
double uniqueness_ratio;
int path_type;
double P1;
double P2;

    bool state;
    std::string name;

    
}groups;



//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int min_disparity;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int disparity_range;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double uniqueness_ratio;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int path_type;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double P1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double P2;
//#line 228 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("LIBSGMConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const LIBSGMConfig &__max__ = __getMax__();
      const LIBSGMConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const LIBSGMConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const LIBSGMConfig &__getDefault__();
    static const LIBSGMConfig &__getMax__();
    static const LIBSGMConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const LIBSGMConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void LIBSGMConfig::ParamDescription<std::string>::clamp(LIBSGMConfig &config, const LIBSGMConfig &max, const LIBSGMConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class LIBSGMConfigStatics
  {
    friend class LIBSGMConfig;

    LIBSGMConfigStatics()
    {
LIBSGMConfig::GroupDescription<LIBSGMConfig::DEFAULT, LIBSGMConfig> Default("Default", "", 0, 0, true, &LIBSGMConfig::groups);
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.min_disparity = -2048;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.min_disparity = 2048;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.min_disparity = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LIBSGMConfig::AbstractParamDescriptionConstPtr(new LIBSGMConfig::ParamDescription<int>("min_disparity", "int", 0, "Disparity to begin search at, pixels (may be negative)", "", &LIBSGMConfig::min_disparity)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LIBSGMConfig::AbstractParamDescriptionConstPtr(new LIBSGMConfig::ParamDescription<int>("min_disparity", "int", 0, "Disparity to begin search at, pixels (may be negative)", "", &LIBSGMConfig::min_disparity)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.disparity_range = 64;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.disparity_range = 256;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.disparity_range = 128;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LIBSGMConfig::AbstractParamDescriptionConstPtr(new LIBSGMConfig::ParamDescription<int>("disparity_range", "int", 0, "Number of disparities to search, pixels", "{'enum_description': 'Selectable options for max disparty', 'enum': [{'srcline': 13, 'description': '64', 'srcfile': '/home/jetson/Self-Driving-Delivery-Robot/src/utils/gpu_stereo_image_proc/cfg/LIBSGM.cfg', 'cconsttype': 'const int', 'value': 64, 'ctype': 'int', 'type': 'int', 'name': '64'}, {'srcline': 14, 'description': '128', 'srcfile': '/home/jetson/Self-Driving-Delivery-Robot/src/utils/gpu_stereo_image_proc/cfg/LIBSGM.cfg', 'cconsttype': 'const int', 'value': 128, 'ctype': 'int', 'type': 'int', 'name': '128'}, {'srcline': 15, 'description': '256', 'srcfile': '/home/jetson/Self-Driving-Delivery-Robot/src/utils/gpu_stereo_image_proc/cfg/LIBSGM.cfg', 'cconsttype': 'const int', 'value': 256, 'ctype': 'int', 'type': 'int', 'name': '256'}]}", &LIBSGMConfig::disparity_range)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LIBSGMConfig::AbstractParamDescriptionConstPtr(new LIBSGMConfig::ParamDescription<int>("disparity_range", "int", 0, "Number of disparities to search, pixels", "{'enum_description': 'Selectable options for max disparty', 'enum': [{'srcline': 13, 'description': '64', 'srcfile': '/home/jetson/Self-Driving-Delivery-Robot/src/utils/gpu_stereo_image_proc/cfg/LIBSGM.cfg', 'cconsttype': 'const int', 'value': 64, 'ctype': 'int', 'type': 'int', 'name': '64'}, {'srcline': 14, 'description': '128', 'srcfile': '/home/jetson/Self-Driving-Delivery-Robot/src/utils/gpu_stereo_image_proc/cfg/LIBSGM.cfg', 'cconsttype': 'const int', 'value': 128, 'ctype': 'int', 'type': 'int', 'name': '128'}, {'srcline': 15, 'description': '256', 'srcfile': '/home/jetson/Self-Driving-Delivery-Robot/src/utils/gpu_stereo_image_proc/cfg/LIBSGM.cfg', 'cconsttype': 'const int', 'value': 256, 'ctype': 'int', 'type': 'int', 'name': '256'}]}", &LIBSGMConfig::disparity_range)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.uniqueness_ratio = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.uniqueness_ratio = 100.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.uniqueness_ratio = 15.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LIBSGMConfig::AbstractParamDescriptionConstPtr(new LIBSGMConfig::ParamDescription<double>("uniqueness_ratio", "double", 0, "Filter out if best match does not sufficiently exceed the next-best match", "", &LIBSGMConfig::uniqueness_ratio)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LIBSGMConfig::AbstractParamDescriptionConstPtr(new LIBSGMConfig::ParamDescription<double>("uniqueness_ratio", "double", 0, "Filter out if best match does not sufficiently exceed the next-best match", "", &LIBSGMConfig::uniqueness_ratio)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.path_type = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.path_type = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.path_type = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LIBSGMConfig::AbstractParamDescriptionConstPtr(new LIBSGMConfig::ParamDescription<int>("path_type", "int", 0, "Scan line directions used during cost aggregation step", "{'enum_description': 'Scan line directions used during cost aggregation step', 'enum': [{'srcline': 24, 'description': 'Aggregate cost from four directions forming a cross', 'srcfile': '/home/jetson/Self-Driving-Delivery-Robot/src/utils/gpu_stereo_image_proc/cfg/LIBSGM.cfg', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'SCAN_4PATH'}, {'srcline': 25, 'description': 'Aggregate cost over all scan lines', 'srcfile': '/home/jetson/Self-Driving-Delivery-Robot/src/utils/gpu_stereo_image_proc/cfg/LIBSGM.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'SCAN_8PATH'}]}", &LIBSGMConfig::path_type)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LIBSGMConfig::AbstractParamDescriptionConstPtr(new LIBSGMConfig::ParamDescription<int>("path_type", "int", 0, "Scan line directions used during cost aggregation step", "{'enum_description': 'Scan line directions used during cost aggregation step', 'enum': [{'srcline': 24, 'description': 'Aggregate cost from four directions forming a cross', 'srcfile': '/home/jetson/Self-Driving-Delivery-Robot/src/utils/gpu_stereo_image_proc/cfg/LIBSGM.cfg', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'SCAN_4PATH'}, {'srcline': 25, 'description': 'Aggregate cost over all scan lines', 'srcfile': '/home/jetson/Self-Driving-Delivery-Robot/src/utils/gpu_stereo_image_proc/cfg/LIBSGM.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'SCAN_8PATH'}]}", &LIBSGMConfig::path_type)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.P1 = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.P1 = 256.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.P1 = 10.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LIBSGMConfig::AbstractParamDescriptionConstPtr(new LIBSGMConfig::ParamDescription<double>("P1", "double", 0, "Smoothness penalty", "", &LIBSGMConfig::P1)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LIBSGMConfig::AbstractParamDescriptionConstPtr(new LIBSGMConfig::ParamDescription<double>("P1", "double", 0, "Smoothness penalty", "", &LIBSGMConfig::P1)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.P2 = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.P2 = 256.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.P2 = 120.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LIBSGMConfig::AbstractParamDescriptionConstPtr(new LIBSGMConfig::ParamDescription<double>("P2", "double", 0, "Discontiguous pennalty", "", &LIBSGMConfig::P2)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LIBSGMConfig::AbstractParamDescriptionConstPtr(new LIBSGMConfig::ParamDescription<double>("P2", "double", 0, "Discontiguous pennalty", "", &LIBSGMConfig::P2)));
//#line 246 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(LIBSGMConfig::AbstractGroupDescriptionConstPtr(new LIBSGMConfig::GroupDescription<LIBSGMConfig::DEFAULT, LIBSGMConfig>(Default)));
//#line 366 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<LIBSGMConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<LIBSGMConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<LIBSGMConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    LIBSGMConfig __max__;
    LIBSGMConfig __min__;
    LIBSGMConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const LIBSGMConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static LIBSGMConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &LIBSGMConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const LIBSGMConfig &LIBSGMConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const LIBSGMConfig &LIBSGMConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const LIBSGMConfig &LIBSGMConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<LIBSGMConfig::AbstractParamDescriptionConstPtr> &LIBSGMConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<LIBSGMConfig::AbstractGroupDescriptionConstPtr> &LIBSGMConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const LIBSGMConfigStatics *LIBSGMConfig::__get_statics__()
  {
    const static LIBSGMConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = LIBSGMConfigStatics::get_instance();

    return statics;
  }

//#line 13 "/home/jetson/Self-Driving-Delivery-Robot/src/utils/gpu_stereo_image_proc/cfg/LIBSGM.cfg"
      const int LIBSGM_64 = 64;
//#line 14 "/home/jetson/Self-Driving-Delivery-Robot/src/utils/gpu_stereo_image_proc/cfg/LIBSGM.cfg"
      const int LIBSGM_128 = 128;
//#line 15 "/home/jetson/Self-Driving-Delivery-Robot/src/utils/gpu_stereo_image_proc/cfg/LIBSGM.cfg"
      const int LIBSGM_256 = 256;
//#line 24 "/home/jetson/Self-Driving-Delivery-Robot/src/utils/gpu_stereo_image_proc/cfg/LIBSGM.cfg"
      const int LIBSGM_SCAN_4PATH = 0;
//#line 25 "/home/jetson/Self-Driving-Delivery-Robot/src/utils/gpu_stereo_image_proc/cfg/LIBSGM.cfg"
      const int LIBSGM_SCAN_8PATH = 1;
}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __LIBSGMRECONFIGURATOR_H__
